apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ipassigner-postgres
  labels:
    app: ipassigner-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipassigner-postgres
  template:
    metadata:
      labels:
        app: ipassigner-postgres
    spec:
      containers:
        - image: 163.143.94.199:5000/rollman/ipassigner_postgres:0.1.0
          name: ipassigner-postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "test"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres_volume
      volumes:
        -name: postgres_volume
        persistentVolumeClaim:
          claimName: claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 2Gi
