apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: slow
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
parameters:
    type: pd-standard
provisioner: kubernetes.io/nfs
