apiVersion: v1
kind: Service
metadata:
  name: service-ipassigner
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30001
  selector:
    app: deployment-ipassigner


